### PR TITLE
GenAI Survey Initial Draft

### PR DESCRIPTION
**Pull request by bettyzhu912**
Please review. 

You can either comment directly in word doc (I've enabled track changes) and upload a new copy in this PR, or simply comment in this PR.

### CODE REVIEW

**Comment by RajuSeetharaman** [comment]
Thank you, Betty.
That's more like it! 
Just a couple of minor comments from me.
1) The 1st line reads as "artifitial" - to be corrected.
2) Not sure how the "£50 Amazon gift card" will work for overseas participants. I can't think of a common gift idea either.

**Comment by DanielRamsayWTW** [comment]
[IFoA GenAI WP Survey.docx](https://github.com/user-attachments/files/15866323/IFoA.GenAI.WP.Survey.docx)

Please review my updates and update the file accordingly

**Comment by DanielRamsayWTW** [comment]
Sorry here is a slightly newer version
[IFoA GenAI WP Survey.docx](https://github.com/user-attachments/files/15866394/IFoA.GenAI.WP.Survey.docx)

**Comment by DrLeiFang** [comment]
Hi all, I read through the survey docx v0.1 and find it excellent! Daniel mentioned it in our last meeting on Friday that we may have too few questions, with Q1-4 mainly on personal info, and only Q5-11 on core stuff. Do you have any more questions in your mind? My suggestion is keeping the current questions, and add options to comment (open questions) if they want to say more.

**Comment by joshua-harper-bzy** [comment]
Overall happy with the survey. I do have a few minor comments:

Question 1 - Seems to be very insurance-focused. I am not sure what someone who works in pensions consulting would choose here. 

Question 3 - Change P&C to General Insurance/Non-Life. General Insurance is generally the terminology used by the IfoA. 

Question 4 - I feel that the difference between entry-level and mid-level seems vague. Perhaps the options of Student and Qualified instead of mid-level?

Question 7 - Add an unsure option for those who are unaware of any policies.

**Comment by DanielRamsayWTW** [comment]
I will do my comments here

change
IFoA Gen AI Working Party Survey 
to
IFoA GenAI Working Party Survey

change
These models leverage deep learning techniques to generate human-like outputs based on natural language processing (NLP), revolutionizing creative processes and augmenting human capabilities across various industries. 
to
These models leverage deep learning techniques to generate human-like outputs, revolutionizing creative processes and augmenting human capabilities across various industries. 

change 
The formation of the IFoA GenAI working party aims to harness the potential of these technologies in a structured and strategic manner. We aim to educate members about the latest developments in GenAI and its applications in the IFoA members practice areas. 
to
By forming IFoA GenAI working party, we aim to harness the potential of these technologies in a structured and strategic manner and to educate members about the latest developments in GenAI and its applications across the various practice areas of the IFoA. 

change
We are also dedicated to exploring, researching, and developing GenAI solutions to drive innovation in this domain.
to 
We are also dedicated to exploring, researching, and developing GenAI solutions to drive innovation in the actuarial and insurance sector.

change 
By leveraging these advanced models and techniques, we hope to encourage innovation and revolutionize actuarial practices, including but not limited to enhancing predictive analytics, offering better customer services, automating complex processing tasks, and ultimately helping to improve the organization’s business decision-making processes and profitability via increased sophistication of analytics and operational efficiencies. 
to
This will include but not be limited to enhancing predictive analytics, offering better customer services, automating complex processing tasks, and ultimately helping to improve the organization’s business decision-making processes and profitability via increased sophistication of analytics and operational efficiencies. 

change
Through this survey, we seek to comprehend how GenAI is being utilized by IFoA members in their respective domains. Additionally, we aim to understand what our members want to see and learn so we can prioritize our research initiatives effectively. By participating, you will help shape the future focus of our work, ensuring that we address the most relevant and impactful topics. 
to
Throughout this survey, we seek to understand how GenAI is being utilized by IFoA members in their respective domains. Additionally, we aim to understand what our members want to see and learn so we can prioritize our research initiatives effectively. By participating, you will help in shaping the future focus of our work, ensuring that we address the most relevant and impactful topics. 

Again simplify this
Q2. What is your firm’s size? [single choice allowed]
A.	1-10 employees
B.	11-50 employees
C.	51-200 employees
D.	201-500 employees
E.	501-1000 employees
F.	1001-5000 employees
G.	5001-10,000 employees
H.	10,001+ employees
to 
Q2. What is your firm’s size? [single choice allowed]
A.	1-100 employees
B.	101-1000 employees
C.	+1001 employees

Change this 
Q4. What is your level of seniority in your current role? [single choice allowed]
A.	Junior-level
B.	Mid-level
C.	Senior-level
D.	Executive/C-suite
to 
Q4. What is your level of seniority in your current role? [single choice allowed]
A.	Junior-level (1-3 years exp.)
B.	Mid-level (3-10 years exp.)
C.	Senior-level (+10 years exp.)
D.	Executive/C-suite

Change
Q12. (if you select D in Q5) What are the frameworks you use for developing GenAI models? (select all that apply)  [multiple choices allowed]
A.	TensorFlow
B.	Keras
C.	PyTorch
D.	LangChain 
to
Q12. (if you select D in Q5) What are the frameworks you use for developing GenAI models? (select all that apply)  [multiple choices allowed]
A.	TensorFlow/Keras
B.	PyTorch
C.	LangChain
D.  LlamaIndex
E.  semantic-kernal


There was some inconsistencies in capitalisation, added extra examples
Change 
Q14. Which topics would you like to learn more about or see more publications on using GenAI? Please rank them by your level of interest (if certain topic is not of your interest, please exclude it from your ranking).   [ranking]
A.	More education about general GenAI trends and knowledge
B.	Data cleansing and manipulation (e.g., guessing missing fields)
C.	Enhancing traditional predictive modeling exercises (e.g., risk and demand modeling)
D.	Reporting generation and analysis (e.g., regulatory compliance) 
E.	Marketing and Sales (e.g., marketing material creation and sales lead generation)
F.	Underwriting (e.g., algorithmic underwriting)
G.	Customer services (e.g., automated policy generation, building bespoke chatbots)
H.	Claims Analytics (e.g., fraud detection)
I.	Coding Assistance 
J.	Others (please specify) _________
to
Q14. Which topics would you like to learn more about or see more publications on using GenAI? Please rank them by your level of interest (if certain topic is not of your interest, please exclude it from your ranking).   [ranking]
A.	More education about general GenAI trends and knowledge
B.	Data cleansing and manipulation (e.g., identifying errors, predicting missing fields)
C.	Enhancing traditional predictive modeling exercises (e.g., risk and demand modeling)
D.	Reporting generation and analysis (e.g., regulatory compliance) 
E.	Marketing and sales (e.g., marketing material creation and sales lead generation)
F.	Underwriting (e.g., algorithmic underwriting)
G.	Customer services (e.g., automated policy generation, building bespoke chatbots)
H.	Claims analytics (e.g., fraud detection)
I.	Coding assistance 
J.	Others (please specify) _________


change
Would you like to join us? If you are interested and if you meet the following qualifications, please upload your resume using the button below, and construct a paragraph around your relevant experience in this domain and motivations. 
to
Would you like to join the GenAI Working Party? If you are interested and if you meet the following qualifications, please upload your resume using the button below, and construct a paragraph around your relevant experience in this domain and motivations.

**Comment by BenDennesen** [comment]
Well done- this is a well structured survey. I have had a read of the survey and cross checked Daniel's comments here. I agree with all of Daniel's comments. 

The only open point from my read is the final question which was discussed in the meeting just now. As was mentioned let's follow IFOA's best practice on this. 

Great work!

**Comment by jain-asmita** [comment]
@bettyzhu912 Have added some comments here
[IFoA GenAI WP Survey.docx](https://github.com/user-attachments/files/16311088/IFoA.GenAI.WP.Survey.docx)

Most changes are to the wording, with some suggestions for rewording some of the options.

**Comment by bettyzhu912** [comment]
@joshua-harper-bzy  @RajuSeetharaman  @DanielRamsayWTW  @DrLeiFang @BenDennesen @cspankaj30  need at least two of you to approve so it can be merged to main branch.

**Review by DanielRamsayWTW — APPROVED** [review]
Looks good

**Review by jain-asmita — APPROVED** [review]

**Pull request merged**
